name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm ci

      - name: Run Migrations for Test
        env:
          PGHOST: localhost
          PGUSER: testuser
          PGPASSWORD: testpassword
          PGDATABASE: testdb
          PGPORT: 5432
        run: npm run migrate

      - name: Run Tests
        env:
          PGHOST: localhost
          PGUSER: testuser
          PGPASSWORD: testpassword
          PGDATABASE: testdb
          PGPORT: 5432
          ACCESS_TOKEN_KEY: test_access_key
          REFRESH_TOKEN_KEY: test_refresh_key
          ACCESS_TOKEN_AGE: 1800
        run: npm run test
